---
# tasks file for roles/image-manipulation

- name: Load distribution-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_lsb.id | default('Undefined') }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_lsb.id | default('Undefined') }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Install snapd
  package:
    name: snapd
    state: present
  become: yes
  when: ansible_distribution == "Linux Mint"

- name: Install pdftk from snap
  snap:
    name: pdftk
    state: present
  become: yes
  when: ansible_distribution == "Linux Mint" or ansible_distribution == "Ubuntu"

# debian: pdftk but from debian-10: pdftk-java
# ubuntu 16.04: pdftk
# CentOS 7 onwards: not available

- name: Install various utilities useful for processing scanned images
  package:
    name: "{{ item }}"
    state: present
  loop:
    - gcc
    - imagemagick
    - mupdf-tools
    - pdfshuffler
    - php
    - php-common
    - php-imagick
    - rawtherapee
  become: yes
