---
- hosts: all
  tasks:
    - name: Install a few packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - acetoneiso
        - munin-node
        - traceroute
        - virt-what
        - wmctrl
      become: yes

  roles:
    - role: anki
    - role: japanese
    - role: developer-tools
    - role: document-tools
    - role: image_manipulation
    - role: utilities

    