---
- hosts: all
  tasks:
    - name: Install a few packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - acpi
        - emacs
        - iotop
        - munin-node
        - nfs-common
        - open-vm-tools
        - sensors-applet
        - tshark
      become: yes

  roles:
    - role: vmware-player
