---
- hosts: all
  tasks:
    - name: Install a few packages
      package:
        name:
        - ack
        - tree
        state: present
      become: yes
  roles:
    - role: collaboration_tools
    - role: developer_tools
    - role: image_manipulation
    - role: utilities
