---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name:  mint-20.1
    image: linuxmintd/mint20.1-amd64
  - name:  mint-19.1
    image: linuxmintd/mint19.1-amd64
  - name:  ubuntu-20.04
    image: ubuntu:20.04
  - name:  ubuntu-18.04
    image: ubuntu:18.04
  - name:  ubuntu-16.04
    image: ubuntu:16.04
provisioner:
  name: ansible
verifier:
  name: testinfra
