---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: ubuntu-18.04
    box: ubuntu/bionic64
  - name: ubuntu-16.04
    box: ubuntu/xenial64
provisioner:
  name: ansible
verifier:
  name: testinfra
