galaxy_info:
  author: Antonio Carlini
  description: Installs tools to help with studying and using Japanese
  license: license (Apache v2.0)
  min_ansible_version: 2.9

  platforms:
    - name: Debian
      versions:
        - 10
        - 9

galaxy_tags: []

dependencies: []
