---
# vars for Ubuntu 20.04

php_intl_package_name: php7.4-intl
php_mbstring_package_name: php7.4-mbstring
php_xml_package_name: php7.4-xml
php_apcu_package_name: php7.4-apcu
php_cli_package_name: php7.4-cli
php_curl_package_name: php7.4-curl 
php_gd_package_name: php7.4-gd
