---
# tasks file for roles/collaboration_tools

- name: Install collaboration tools debian systems
  apt:
    deb: "{{ item }}"
  become: yes
  loop:
     - https://go.skype.com/skypeforlinux-64.deb
     - https://downloads.slack-edge.com/linux_releases/slack-desktop-4.0.2-amd64.deb
     - https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.3.00.30857_amd64.deb
     - https://zoom.us/client/latest/zoom_amd64.deb
  when: ansible_pkg_mgr == "apt"

- name: Install collaboration for RedHat systems
  yum:
    name: "{{ item }}"
    disable_gpg_check: yes
  become: yes
  loop:
     # - https://go.skype.com/skypeforlinux-64.rpm
     - https://downloads.slack-edge.com/linux_releases/slack-4.0.2-0.1.fc21.x86_64.rpm
     - https://packages.microsoft.com/yumrepos/ms-teams/teams-1.3.00.30857-1.x86_64.rpm
     - https://zoom.us/client/latest/zoom_x86_64.rpm
  when: (ansible_pkg_mgr == "yum") or (ansible_pkg_mgr == "dnf")
