---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: mint-19
    box: boxcycler/linuxmint-19-cinnamon-64bit-v2-release
  - name: debian-10
    box: debian/buster64
  - name: ubuntu-18.04
    box: ubuntu/bionic64
  - name: ubuntu-16.04
    box: ubuntu/xenial64
  - name: centos-8
    box: centos/8
provisioner:
  name: ansible
verifier:
  name: testinfra
