---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: mint-19
    box: boxcycler/linuxmint-19-cinnamon-64bit-v2-release
  - name: ubuntu-18.04
    box: ubuntu/bionic64
  - name: ubuntu-16.04
    box: ubuntu/xenial64
  - name: debian-9
    box: debian/stretch64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
