---
# tasks file for roles/mysql

- name: Load distribution-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_lsb.id | default('Undefined') }}-{{ ansible_distribution_major_version }}.yml"     # e.g. "Linuxmint-20.yml"
    - "{{ ansible_distribution }}.yml"                                                               # e.g. "Linux Mint.yml"
    - "{{ ansible_os_family }}.yml"                                                                  # e.g. "Debian.yml"

- name: Install a MySQL database (mariadb)
  package:
    state: present
    name:
      - automysqlbackup
      - mariadb-server
      - "{{ python_venv }}"
      - "{{ python_pip }}"
      - "{{ python_setuptools }}"
      - "{{ python_dev }}"
      - "{{ python_mysql }}"
  become: yes

- name: List pip modules
  command: '{{ pip_command }} list'
  changed_when: no
  register: pip_list

- name: Install pymysql
  pip:
    name: PyMySQL
  when: not "PyMySQL" in pip_list.stdout

- include_tasks: secure-mysql.yml
  tags:
    - security

- include_tasks: warn_password.yml
  tags:
    - security

