---
# tasks file for roles/mysql

- name: Load distribution-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Install a MySQL database (mariadb)
  package:
    state: present
    name:
      - automysqlbackup
      - mariadb-server
      - python-dev
      - python-mysqldb
      - python-pip
      - python3-venv
      - python3-pip
      - python-setuptools
      - python3-setuptools
      - "{{ python_mysql }}"
  become: yes

- name: List pip modules
  command: pip list
  changed_when: no
  register: pip_list

- name: Install pymysql
  pip:
    name: PyMySQL
  when: not "PyMySQL" in pip_list.stdout

- include_tasks: secure-mysql.yml
  tags:
    - security

- include_tasks: warn_password.yml
  tags:
    - security

