---

# Once mysql has been installed, these tasks secure the installation

- name: Set the MySQL admin password
  mysql_user:
    login_user: root
    login_password: ""
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: 'localhost'
    user: "{{ mysql_admin_user }}"
    password: "{{ mysql_admin_password }}"
    priv: "*.*:ALL"
  become_method: sudo
  become: yes

- name: Secure the admin user for IPV6 localhost (::1), IPv4 localhost, localhost and the server's domain
  mysql_user:
    login_user: "{{ mysql_admin_user }}"
    login_password: "{{ mysql_admin_password }}"
    user: admin
    password: "{{ mysql_admin_password }}"
    host: "{{ item }}"
  become: yes
  loop:
    - "::1"
    - "127.0.0.1"
    - "localhost"
    - "{{ ansible_fqdn }}"

- name: Deletes anonymous server user
  mysql_user:
    login_user: "{{ mysql_admin_user }}"
    login_password: "{{ mysql_admin_password }}"
    user: ""
    host_all: yes
    state: absent
  become: yes

- name: Removes the test database
  mysql_db:
    login_user: "{{ mysql_admin_user }}"
    login_password: "{{ mysql_admin_password }}"
    db: test
    state: absent
  become: yes
