---

# Issue a warning if the default root password has not been changed
# Encapsulate the warning here so it can be used in multiple places if needed

- name: Check for non-default root password
  debug:
    msg: "WARNING: Set a root password, for example on the command line --extra-vars \"mysql_admin_password=SUITABLE_PASSWORD\""
  when: mysql_insecure_admin_password == mysql_admin_password
