---
galaxy_info:
  author: Antonio Carlini
  description: Installs a DNS server
  license: license (Apache v2.0)
  min_ansible_version: 2.9

  platforms:
    - name: Linux Mint
      versions:
        - 21
  galaxy_tags: []

dependencies: []
