---
galaxy_info:
  author: Antonio Carlini
  description: Installs developer tools for a specified account
  license: license (Apache v2.0)
  min_ansible_version: 2.9

  platforms:
    - name: Linux Mint
      versions:
        - 20.1
        - 19.1
    - name: Ubuntu
      versions:
        - 20.04
        - 18.04
        - 16.04
    - name: Debian
      versions:
        - 10
        - 9
    - name: CentOS
      versions:
        - 8
        - 7
  galaxy_tags: []

dependencies: []
