galaxy_info:
  author: Antonio Carlini
  description: Installs those tools most often needed for dealing with documents (i.e. office tools).
  license: license (Apache v2.0)
  min_ansible_version: 2.9

  platforms:
    - name: Debian
      versions:
        - 10
        - 9
        - 8
    - name: Ubuntu
      versions:
        - 18.04
        - 16.04
    - name: CentOS
      versions:
        - 7

  galaxy_tags: []

dependencies: []
