---
# tasks to fix locale. Ensures that en_GB is a valid locale

- name: Fix locale
  lineinfile:
    dest: /etc/environment
    line: "{{ item }}"
    state: present
  with_items:
    - LC_ALL=en_GB.UTF-8
    - LANG=en_GB.UTF-8
  become: yes

- name: Set for en_GB
  lineinfile:
    dest: /etc/locale.gen
    regexp: "#.*en_GB"
    line: en_GB.UTF-8 UTF-8
  become: yes

- name: Generate locale
  command: locale-gen
  become: yes


