---
# tasks file for roles/utilities

# TODO:  anoise-gui fails to install
# TODO:  keypass2 fails to install

- name: Add anoise PPA
  apt_repository:
    repo: ppa:costales/anoise
  become: yes

- name: Install various utilities
  package:
    name:
      - anoise
    state: present
  become: yes
