---
# tasks file for visual_studio_code

# CentOS needs the EPEL repository to find (e.g.) libX11-devel
- name: Install EPEL repository for CentOS
  package:
    name: epel-release
    state: present
  become: yes
  when: ansible_os_family == "RedHat"

- name: Read platform-dependent variables
  include_vars: "{{ item }}"
  with_fileglob:
        - "vars/{{ ansible_os_family }}-family.yml"
        - "vars/{{ ansible_distribution | replace(' ','') }}.yml"
        - "vars/{{ ansible_distribution | replace(' ','') }}-{{ ansible_distribution_major_version }}.yml"

# Install Visual Studio Code on the system
- include_tasks: vscode_system_setup.yml

# Include VS Code extensions for a specific user, if a specific user is specified
- include_tasks: vscode_extensions.yml
  when: (user_account is defined)
