---
# tasks file for ntp-client

- name: Update apt
  apt:
    update_cache: yes
  become: yes
  when: ansible_pkg_mgr == "apt"
  changed_when: False

- name: Install ntp client
  package:
    name:
      - ntp
      - ntpstat
    state: present
  become: yes

- name: Start ntp
  systemd:
    name: ntp
    state: started
    enabled: yes
  become: yes

