---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: mint-20
    box: aaronvonawesome/linux-mint-20-cinnamon
  - name: mint-19
    box: boxcycler/linuxmint-19-cinnamon-64bit-v2-release
  - name: debian-10
    box: debian/buster64
  - name: debian-9
    box: debian/stretch64
  - name: ubuntu-20.04
    box: ubuntu/focal64
  - name: ubuntu-18.04
    box: ubuntu/bionic64
  - name: ubuntu-16.04
    box: ubuntu/xenial64
provisioner:
  name: ansible
verifier:
  name: testinfra
