---
# tasks file for nix

- name: Install required packages
  package:
    name:
      - curl                      # needed by nix-shell
    state: present
  become: yes

- name: Install required apt packages
  package:
    name:
      - xz-utils
    state: present
  become: yes
  when: ansible_pkg_mgr == "apt"

# ''user_account' must be defined by whoever runs the ansible script
- name: Check that user_account has been specified
  fail:
    msg: 'Set user_account using -e "user_account=USERACCOUNT"'
  when: (not user_account is defined)

- name: Get the nix-shell installer
  get_url:
    url: https://nixos.org/nix/install
    dest: /tmp/nix-shell.install

# The nix install will try to create the /nix directory using sudo.
# That's only going to work if the user account is setup for passwordless sudo.
# So avoid the issue by creating the /nix directory for the user (with the approrpiate ownership)

- name: Create nix directory for specified user
  file:
    path: /nix
    group: "{{ user_account }}"
    owner: "{{ user_account }}"
    state: directory
  become: yes

- name: Run the nix-shell installer
  command: sh /tmp/nix-shell.install
  args:
    creates: /nix/var
  become: yes
  become_user: "{{ user_account }}"
