---
# tasks file for anki

- name: Load distribution-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Update apt
  apt:
    update_cache: yes
  become: yes
  when: ansible_pkg_mgr == "apt"
  changed_when: False

- name: Install gnu make (and others)
  package:
    name: "{{ item }}"
    state: present
  loop:
    - xdg-utils
    - " {{ make_package }}"
  become: yes

- name: Fetch anki tarball
  get_url:
    url: "https://github.com/ankitects/anki/releases/download/{{ anki_version }}/anki-{{anki_version }}-linux-amd64.tar.bz2"
    dest: /tmp/anki.tar.bz2




- name: Check to see if the tarball has already been expanded
  stat:
    path: /tmp/anki-{{ anki_version }}-linux-amd64
  register: anki_archive_expanded

- name: Expand anki tarball
  unarchive:
    remote_src: yes
    src: /tmp/anki.tar.bz2
    dest: /tmp
  when: not anki_archive_expanded.stat.exists

- name: Record the time of the anki Makefile (if it exists)
  stat:
    path: /usr/local/share/anki/Makefile
  register : usr_local_anki_makefile

- name: Record the time of the installed anki Makefile
  stat:
    path: "/tmp/anki-{{ anki_version }}-linux-amd64/Makefile"
  register : installer_anki_makefile

- name: Build and install anki
  command : make -C "/tmp/anki-{{ anki_version }}-linux-amd64" install
  when: (not usr_local_anki_makefile.stat.exists) or (usr_local_anki_makefile.stat.mtime != installer_anki_makefile.stat.mtime)
  become: yes
