---
# tasks file for roles/php

- name: Load distribution-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_lsb.id | default('Undefined') }}-{{ ansible_distribution_major_version }}.yml"     # e.g. "Linuxmint-20.yml"
    - "{{ ansible_lsb.id | default('Undefined') }}.yml"                                              # e.g. "Linuxmint.yml"
    - "{{ ansible_distribution }}.yml"                                                               # e.g. "Linux Mint.yml"
    - "{{ ansible_os_family }}.yml"                                                                  # e.g. "Debian.yml"
    - "default.yml"

- name: "Add universe repos for Ubuntu bionic/xenial"
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} main universe"
    - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security main universe"
    - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates main universe"
  when: (ansible_distribution == "Ubuntu") and ((ansible_distribution_major_version == "18") or (ansible_distribution_major_version == "16"))
  become: yes

- name: Install PHP
  package:
    name:
      - "{{ php_intl_package_name }}"
      - "{{ php_mbstring_package_name }}"
      - "{{ php_xml_package_name }}"
      - "{{ php_apcu_package_name }}"
      - "{{ php_cli_package_name }}"
      - "{{ php_curl_package_name }}"
      - "{{ php_gd_package_name }}"
    state: present
  become: yes

