---
# tasks file for roles/webserver

- name: Include platform-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install a web server (apache) for mediawiki
  package:
    name:
      - "{{ webserver_package }}"
      - "{{ mod_php_package }}"
    state: present
  loop:
  become: yes
