---
# tasks file for roles/developer-tools

- name: Install Standard Packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - emacs
    - ruby
    - tree
  become: yes
  
- include_tasks: nix-shell.yml

- include_tasks: rust.yml

- include_tasks: visual-studio-code.yml

