---
# tasks file for roles/developer-tools

# nix-shell needs curl installed. Not all distributions include it (e.g. debian minimal install), so install it here.

- name: Install Standard Packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - curl                      # needed by nix-shell
    - emacs
    - git
    - gnome-terminal
    - python
    - python-pip
    - ruby
    - tree
  become: yes
  tags:
    - packages

- name: Ensure pip is up to date
  shell: pip install --upgrade setuptools
  tags:
    - packages
    - pip
    - git

- name: Install pre-commit for git
  pip:
    name: pre-commit
  tags:
    - packages
    - git

- include_tasks: nix-shell.yml
  tags:
    - nix

- include_tasks: rust.yml
  tags:
    - rust

- include_tasks: visual-studio-code.yml
  tags:
    - vscode

