---
# tasks file for roles/developer-tools

# Either 'system_only' must be true or 'user_account' must be defined.
- name: Check that required variables are consistent
  fail:
    msg: "system_account variable is false but user_account is not defined. Set one of the other using -e"
  when: (not user_account is defined) and (not system_only)

# CentOS needs the EPEL repository to find python-pip
- name: Install EPEL repository for CentOS
  package:
    name: epel-release
    state: present
  become: yes
  when: ansible_os_family == "RedHat"

# Ubuntu needs the universe repository to find python-pip
- name: "Add universe repos for Ubuntu bionic/xenial"
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} main universe"
    - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security main universe"
    - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates main universe"
  when: ansible_distribution == "Ubuntu"
  become: yes

# Ubuntu will not run pip properly if the local is wrong, so try to fix it
- name: "Fix locale"
  locale_gen:
    name: en_GB.UTF-8
    state: present
  when: ansible_distribution == "Ubuntu"
  become: yes

# nix-shell needs curl installed. Not all distributions include it (e.g. debian minimal install), so install it here.

- name: Install packages
  package:
    name:
      - curl                      # needed by nix-shell
      - emacs
      - git
      - gnome-terminal
      - python
      - python-pip
      - python-setuptools
      - python3
      - python3-pip
      - python3-setuptools
      - ruby
      - tree
    state: present
  become: yes
  tags:
    - packages

- name: List modules using pip
  command: pip list
  changed_when: no
  register: pip_list

- name: List modules using pip3
  command: pip3 list
  changed_when: no
  register: pip3_list

- name: Install pre-commit for git
  pip:
    name: pre-commit
  when: (not pip_list.stdout is search("pre-commit")) and (not pip3_list.stdout is search("pre-commit"))
  tags:
    - packages
    - git

- include_tasks: visual-studio-code.yml
  tags:
    - vscode

- include_tasks: user-account-setup.yml
  when: not system_only
