---
# tasks file for roles/developer-tools

# nix-shell needs curl installed. Not all distributions include it (e.g. debian minimal install), so install it here.

- name: Install Standard Packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - emacs
    - ruby
    - tree
    - curl                      # needed by nix-shell
    - python
    - python-pip
  become: yes
  
- name: Ensure pip is up to date
  shell: pip install --upgrade setuptools

- name: Install pre-commit for git
  pip:
    name: pre-commit

- include_tasks: nix-shell.yml

- include_tasks: rust.yml

- include_tasks: visual-studio-code.yml

