---
# tasks to install rust

- name: Install packages for rust
  package:
    name: "{{ item }}"
    state: present
  loop:
    - libc6-dev
  become: yes

- name: Get the rust installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs

- name: Run the rust installer
  command: sh /tmp/sh.rustup.rs -y
