---
# tasks to install Visual Studio Code Extensions

# This is a per-user installation.

- name: Check for Visual Studio Code extensions
  command: code --list-extensions
  changed_when: false
  register: vscode_extensions

# To make this code idempotent, avoid installing if one extension is already present
- name: Install extensions for Visual Studio Code
  command: code --install-extension "{{ item }}"
  when: not item in vscode_extensions.stdout
  loop:
    - DavidAnson.vscode-markdownlint
    - KnisterPeter.vscode-github
    - atlassian.atlascode
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-vscode-remote.vscode-remote-extensionpack
    - ms-vscode.cpptools
    - redhat.vscode-yaml
    - rust-lang.rust
