---
# tasks file for roles/mediawiki

# TODO
# Handle mediawiki extensions
# mediawiki extensions ...
#Cite (no need beyond 1.26)
#ParserFunctions
# EasyTimeline


- name: Install packages required for mediawiki
  package:
    name: "{{ item }}"
    state: present
  loop:
    - fonts-freefont-ttf
    - imagemagick
    - inkscape
  become: yes

- name: Install PHP
  include_role:
    name: php

- name: Install a MySQL database
  include_role:
    name: mysql

- name: Install a webserver
  include_role:
    name: webserver


- name: Create the mediawiki temp directory
  file:
    path: /tmp/mediawiki
    state: directory

- name: Fetch and expand mediawiki tarball
  unarchive:
    remote_src: yes
    src: https://releases.wikimedia.org/mediawiki/1.34/mediawiki-1.34.0.tar.gz
    dest: /tmp/mediawiki

- name: Create the mediawiki directory
  file:
    path: /var/lib/mediawiki
    state: directory
  become: yes

- name: Install mediawiki
  shell : |
    cd /tmp/mediawiki
    sudo mv mediawiki-*/* /var/lib/mediawiki
  args:
    creates: /var/lib/mediawiki
  become: yes