---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: mint-20
    box: aaronvonawesome/linux-mint-20-cinnamon
  - name: mint-19
    box: boxcycler/linuxmint-19-cinnamon-64bit-v2-release
  - name: ubuntu-20-04
    box: ubuntu/focal64
  - name: ubuntu-18-04
    box: ubuntu/bionic64
  - name: debian-10
    box: debian/buster64
provisioner:
  name: ansible
  options:
    e: mysql_admin_password=SUITABLE_PASSWORD
verifier:
  name: testinfra
